from __future__ import annotations

import sqlite3
import hashlib
import hmac
import base64
import binascii
import json
import logging
import os
import re
import secrets
from datetime import datetime, timedelta, timezone
from pathlib import Path

from functools import wraps

from flask import Flask, abort, jsonify, redirect, request, send_from_directory, session
from sqlalchemy import create_engine
from sqlalchemy.exc import IntegrityError
from werkzeug.security import check_password_hash, generate_password_hash

BASE_DIR = Path(__file__).resolve().parent
IS_VERCEL = bool(os.environ.get("VERCEL"))
DATABASE_URL = os.environ.get("DATABASE_URL", "sqlite:///app.db").strip()
if DATABASE_URL.startswith("postgres://"):
    DATABASE_URL = "postgresql+psycopg2://" + DATABASE_URL[len("postgres://"):]
elif DATABASE_URL.startswith("postgresql://"):
    DATABASE_URL = "postgresql+psycopg2://" + DATABASE_URL[len("postgresql://"):]
engine = create_engine(
    DATABASE_URL,
    pool_pre_ping=True,
    connect_args={"check_same_thread": False} if DATABASE_URL.startswith("sqlite:") else {},
)
IS_POSTGRES = DATABASE_URL.startswith("postgresql")
HAS_PERSISTENT_DATABASE = IS_POSTGRES
ID_COLUMN = "id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" if IS_POSTGRES else "id INTEGER PRIMARY KEY AUTOINCREMENT"
STUDENT_EMAIL_PATTERN = re.compile(r"^[a-z0-9._%+-]+cse@nsec\.ac$", re.IGNORECASE)
MAX_STUDENTS = 10
MAX_ADMINS = 2

app = Flask(__name__, static_folder=None)
app.config.update(
    SECRET_KEY=os.environ.get("CAMPUSPULSE_SECRET_KEY", "dev-only-change-this-secret"),
    SESSION_COOKIE_HTTPONLY=True,
    SESSION_COOKIE_SAMESITE="Lax",
    SESSION_COOKIE_SECURE=os.environ.get("CAMPUSPULSE_SECURE_COOKIES", "0") == "1",
    PERMANENT_SESSION_LIFETIME=timedelta(minutes=30),
)
app.logger.setLevel(logging.INFO)


@app.after_request
def security_headers(response):
    response.headers["X-Content-Type-Options"] = "nosniff"
    response.headers["X-Frame-Options"] = "DENY"
    response.headers["Referrer-Policy"] = "no-referrer"
    response.headers["Content-Security-Policy"] = "default-src 'self' https://cdn.jsdelivr.net; script-src 'self' https://cdn.jsdelivr.net 'unsafe-inline' 'unsafe-eval' 'wasm-unsafe-eval'; style-src 'self' 'unsafe-inline'; connect-src 'self' https://cdn.jsdelivr.net blob:; worker-src 'self' blob:"
    return response


class CompatibleRow(dict):
    def __getitem__(self, key):
        if isinstance(key, int):
            return list(self.values())[key]
        return super().__getitem__(key)


class CompatibleResult:
    def __init__(self, result):
        self.result = result
        self.lastrowid = getattr(result, "lastrowid", None)

    def fetchone(self):
        row = self.result.fetchone()
        return CompatibleRow(row._mapping) if row is not None else None

    def fetchall(self):
        return [CompatibleRow(row._mapping) for row in self.result.fetchall()]


class DatabaseConnection:
    def __init__(self):
        self.connection = engine.connect()

    def execute(self, statement, parameters=()):
        if IS_POSTGRES:
            statement = statement.replace("?", "%s")
        return CompatibleResult(self.connection.exec_driver_sql(statement, tuple(parameters)))

    def commit(self):
        self.connection.commit()

    def __enter__(self):
        return self

    def __exit__(self, exception_type, exception_value, traceback):
        if exception_type:
            self.connection.rollback()
        self.connection.close()


def get_conn() -> DatabaseConnection:
    return DatabaseConnection()


def init_db() -> None:
    with get_conn() as conn:
        conn.execute(
            f"""
            CREATE TABLE IF NOT EXISTS focus_sessions (
                {ID_COLUMN},
                username TEXT NOT NULL,
                focused_percentage REAL NOT NULL,
                distracted_percentage REAL NOT NULL,
                focused_seconds INTEGER NOT NULL,
                distracted_seconds INTEGER NOT NULL,
                total_seconds INTEGER NOT NULL,
                session_started_at TEXT NOT NULL,
                session_ended_at TEXT NOT NULL,
                created_at TEXT NOT NULL
            )
            """
        )
        conn.execute(
            f"""
            CREATE TABLE IF NOT EXISTS self_analysis_logs (
                {ID_COLUMN},
                username TEXT NOT NULL,
                log_date TEXT NOT NULL,
                study_hours REAL NOT NULL,
                coding_hours REAL NOT NULL,
                gaming_hours REAL NOT NULL,
                physical_activity_hours REAL NOT NULL,
                social_media_hours REAL NOT NULL,
                created_at TEXT NOT NULL,
                UNIQUE(username, log_date)
            )
            """
        )
        conn.execute(
            f"""
            CREATE TABLE IF NOT EXISTS users (
                {ID_COLUMN},
                username TEXT UNIQUE NOT NULL,
                email TEXT UNIQUE NOT NULL,
                full_name TEXT NOT NULL DEFAULT '',
                role TEXT NOT NULL DEFAULT 'student',
                hostel TEXT NOT NULL DEFAULT 'Unassigned',
                token_id TEXT NOT NULL DEFAULT '',
                password_hash TEXT NOT NULL,
                department TEXT NOT NULL,
                study_year INTEGER NOT NULL,
                is_admin INTEGER NOT NULL DEFAULT 0,
                is_verified INTEGER NOT NULL DEFAULT 0,
                mfa_secret TEXT NOT NULL,
                created_at TEXT NOT NULL
            )
            """
        )
        if IS_POSTGRES:
            for statement in (
                "ALTER TABLE users ADD COLUMN IF NOT EXISTS full_name TEXT NOT NULL DEFAULT ''",
                "ALTER TABLE users ADD COLUMN IF NOT EXISTS role TEXT NOT NULL DEFAULT 'student'",
                "ALTER TABLE users ADD COLUMN IF NOT EXISTS hostel TEXT NOT NULL DEFAULT 'Unassigned'",
                "ALTER TABLE users ADD COLUMN IF NOT EXISTS token_id TEXT NOT NULL DEFAULT ''",
            ):
                conn.execute(statement)
        else:
            columns = {row["name"] for row in conn.execute("PRAGMA table_info(users)").fetchall()}
            for name, definition in (("full_name", "TEXT NOT NULL DEFAULT ''"), ("role", "TEXT NOT NULL DEFAULT 'student'"), ("hostel", "TEXT NOT NULL DEFAULT 'Unassigned'"), ("token_id", "TEXT NOT NULL DEFAULT ''")):
                if name not in columns:
                    conn.execute(f"ALTER TABLE users ADD COLUMN {name} {definition}")
        conn.execute("UPDATE users SET role = CASE WHEN is_admin = 1 THEN 'admin' ELSE 'student' END WHERE role IS NULL OR role = ''")
        conn.execute("UPDATE users SET hostel = 'Unassigned' WHERE hostel IS NULL OR hostel = ''")
        rows_without_tokens = conn.execute("SELECT id FROM users WHERE token_id = '' OR token_id IS NULL").fetchall()
        for row in rows_without_tokens:
            conn.execute("UPDATE users SET token_id = ? WHERE id = ?", (secrets.token_urlsafe(24), row["id"]))
        conn.execute(
            f"""
            CREATE TABLE IF NOT EXISTS predictions (
                {ID_COLUMN},
                user_id INTEGER NOT NULL,
                stress_level TEXT NOT NULL,
                score REAL NOT NULL,
                created_at TEXT NOT NULL,
                FOREIGN KEY(user_id) REFERENCES users(id)
            )
            """
        )
        conn.execute(
                """INSERT INTO users
               (username, email, password_hash, department, study_year, is_admin,
                is_verified, mfa_secret, created_at)
                    VALUES (?, ?, ?, ?, ?, 1, 1, ?, ?)
                    ON CONFLICT (username) DO NOTHING""",
            (
                "admin",
                "admin@campuspulse.local",
                generate_password_hash(os.environ.get("CAMPUSPULSE_ADMIN_PASSWORD", "AdminChangeMe!1")),
                "CSE",
                1,
                hashlib.sha256(os.environ.get("CAMPUSPULSE_ADMIN_MFA", "admin-demo-mfa").encode()).hexdigest(),
                datetime.now(timezone.utc).isoformat(),
            ),
        )
        conn.execute("UPDATE users SET mfa_secret = ? WHERE username = 'admin'", (hashlib.sha256(os.environ.get("CAMPUSPULSE_ADMIN_MFA", "admin-demo-mfa").encode()).hexdigest(),))
        conn.execute(
            """INSERT INTO users
               (username, email, full_name, role, hostel, token_id, password_hash, department, study_year, is_admin,
                is_verified, mfa_secret, created_at)
               VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, 0, 1, ?, ?)
               ON CONFLICT (username) DO NOTHING""",
            (
                "guest",
                "guest@campuspulse.local",
                "Guest",
                "student",
                "Unassigned",
                secrets.token_urlsafe(24),
                generate_password_hash(secrets.token_urlsafe(32)),
                "CSE",
                1,
                hashlib.sha256(secrets.token_urlsafe(32).encode()).hexdigest(),
                datetime.now(timezone.utc).isoformat(),
            ),
        )
        conn.commit()


def current_user() -> sqlite3.Row | None:
    authorization = request.headers.get("Authorization", "")
    if authorization.startswith("Bearer "):
        return user_from_token(authorization[7:].strip())
    user_id = session.get("user_id")
    if not user_id:
        return None
    with get_conn() as conn:
        return conn.execute("SELECT * FROM users WHERE id = ?", (user_id,)).fetchone()


def require_auth(admin: bool = False):
    def decorator(function):
        @wraps(function)
        def wrapped(*args, **kwargs):
            user = current_user()
            if user is None:
                return jsonify({"error": "authentication required"}), 401
            if admin and not user["is_admin"]:
                return jsonify({"error": "administrator access required"}), 403
            return function(*args, **kwargs)
        return wrapped
    return decorator


def valid_csrf() -> bool:
    authorization = request.headers.get("Authorization", "")
    if authorization.startswith("Bearer ") and user_from_token(authorization[7:].strip()) is not None:
        return True
    token = request.headers.get("X-CSRF-Token", "")
    expected = session.get("csrf_token", "")
    return bool(token and expected and hmac.compare_digest(token, expected))


def encode_token(user: dict) -> str:
    header = {"alg": "HS256", "typ": "JWT"}
    payload = {"sub": str(user["id"]), "role": user["role"], "jti": user["token_id"], "exp": int((datetime.now(timezone.utc) + timedelta(hours=12)).timestamp())}
    def part(value):
        return base64.urlsafe_b64encode(json.dumps(value, separators=(",", ":")).encode()).rstrip(b"=").decode()
    unsigned = part(header) + "." + part(payload)
    signature = hmac.new(app.config["SECRET_KEY"].encode(), unsigned.encode(), hashlib.sha256).digest()
    return unsigned + "." + base64.urlsafe_b64encode(signature).rstrip(b"=").decode()


def user_from_token(token: str):
    try:
        encoded_header, encoded_payload, encoded_signature = token.split(".")
        unsigned = encoded_header + "." + encoded_payload
        expected = base64.urlsafe_b64encode(hmac.new(app.config["SECRET_KEY"].encode(), unsigned.encode(), hashlib.sha256).digest()).rstrip(b"=").decode()
        if not hmac.compare_digest(expected, encoded_signature):
            return None
        payload = json.loads(base64.urlsafe_b64decode(encoded_payload + "=" * (-len(encoded_payload) % 4)))
        if int(payload["exp"]) < int(datetime.now(timezone.utc).timestamp()):
            return None
        with get_conn() as conn:
            user = conn.execute("SELECT * FROM users WHERE id = ? AND token_id = ?", (int(payload["sub"]), payload["jti"])).fetchone()
        return user
    except (ValueError, KeyError, TypeError, json.JSONDecodeError, binascii.Error):
        return None


def csrf_required(function):
    @wraps(function)
    def wrapped(*args, **kwargs):
        if not valid_csrf():
            return jsonify({"error": "invalid security token"}), 403
        return function(*args, **kwargs)
    return wrapped


def authenticate_user(user, remember=True):
    if remember:
        session.clear()
        session.permanent = True
        session["user_id"] = user["id"]
        session["csrf_token"] = secrets.token_urlsafe(32)
    return encode_token(user)


def cleanup_old_rows(conn: sqlite3.Connection) -> None:
    cutoff = (datetime.now(timezone.utc) - timedelta(days=30)).isoformat()
    conn.execute("DELETE FROM focus_sessions WHERE created_at < ?", (cutoff,))
    conn.execute("DELETE FROM self_analysis_logs WHERE created_at < ?", (cutoff,))


@app.route("/api/session", methods=["GET"])
def session_info() -> object:
    session.setdefault("csrf_token", secrets.token_urlsafe(32))
    user = current_user()
    return jsonify({
        "authenticated": user is not None,
        "username": user["username"] if user else None,
        "is_admin": bool(user["is_admin"]) if user else False,
        "csrf_token": session["csrf_token"],
        "token": encode_token(user) if user else None,
    })


@app.route("/api/health", methods=["GET"])
def health() -> object:
    return jsonify({
        "status": "ok",
        "database": "postgresql" if IS_POSTGRES else "sqlite",
        "persistent_database_configured": HAS_PERSISTENT_DATABASE,
        "message": "Set DATABASE_URL in Vercel." if IS_VERCEL and not HAS_PERSISTENT_DATABASE else "ready",
    }), 200


@app.route("/api/signup", methods=["POST"])
@csrf_required
def signup() -> object:
    if IS_VERCEL and not HAS_PERSISTENT_DATABASE:
        return jsonify({"error": "Persistent database is not configured. Add DATABASE_URL in Vercel and redeploy."}), 503
    payload = request.get_json(silent=True) or {}
    username = str(payload.get("username", "")).strip()
    full_name = str(payload.get("full_name", username)).strip() or username
    email = str(payload.get("email", "")).strip().lower()
    password = str(payload.get("password", ""))
    role = str(payload.get("role", "student")).strip().lower()
    hostel = str(payload.get("hostel", "Unassigned")).strip() or "Unassigned"
    department = str(payload.get("department", "")).strip().upper()
    try:
        study_year = int(payload.get("study_year", 0))
    except (TypeError, ValueError):
        study_year = 0
    if len(username) < 3 or len(username) > 40 or not username.replace("_", "").isalnum():
        return jsonify({"error": "Choose a valid username."}), 400
    if role not in {"student", "admin"} or "@" not in email or len(password) < 10 or department != "CSE" or study_year not in (1, 2, 3, 4):
        return jsonify({"error": "Enter valid account details and a password of at least 10 characters."}), 400
    if role == "student" and not STUDENT_EMAIL_PATTERN.fullmatch(email):
        return jsonify({"error": "Students must use a college email like usernamecse@nsec.ac."}), 400
    with get_conn() as conn:
        try:
            count_query = "SELECT COUNT(*) AS count FROM users WHERE is_admin = ?"
            count_parameters = (1 if role == "admin" else 0,)
            if role == "student":
                count_query += " AND username <> 'guest'"
            count = conn.execute(count_query, count_parameters).fetchone()["count"]
            limit = MAX_ADMINS if role == "admin" else MAX_STUDENTS
            if count >= limit:
                return jsonify({"error": ("Admin" if role == "admin" else "Student") + " account limit reached."}), 409
            token_id = secrets.token_urlsafe(24)
            conn.execute(
                """INSERT INTO users
                   (username, email, full_name, role, hostel, token_id, password_hash, department, study_year, is_admin, is_verified, mfa_secret, created_at)
                   VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 1, ?, ?)""",
                (username, email, full_name, role, hostel, token_id, generate_password_hash(password), department, study_year,
                 1 if role == "admin" else 0, hashlib.sha256(secrets.token_urlsafe(24).encode()).hexdigest(), datetime.now(timezone.utc).isoformat()),
            )
            conn.commit()
        except IntegrityError:
            return jsonify({"error": "Unable to create account with those details."}), 400
        user = conn.execute("SELECT * FROM users WHERE token_id = ?", (token_id,)).fetchone()
    token = authenticate_user(user)
    app.logger.info("signup created username=%s role=%s", username, role)
    return jsonify({"message": "Account created.", "token": token, "role": role, "redirect": "admin.html" if role == "admin" else "home.html"})


@app.route("/api/signin", methods=["POST"])
@csrf_required
def signin() -> object:
    payload = request.get_json(silent=True) or {}
    username = str(payload.get("username", "")).strip()
    password = str(payload.get("password", ""))
    mfa_code = str(payload.get("mfa_code", "")).strip()
    with get_conn() as conn:
        user = conn.execute("SELECT * FROM users WHERE username = ? OR email = ?", (username, username.lower())).fetchone()
    if user is None or not check_password_hash(user["password_hash"], password):
        return jsonify({"error": "Invalid credentials."}), 401
    requested_role = str(payload.get("role", "student")).strip().lower()
    actual_role = "admin" if user["is_admin"] else "student"
    if requested_role != actual_role:
        return jsonify({"error": "The selected account type does not match this account."}), 403
    if user["is_admin"] and mfa_code:
        if not hmac.compare_digest(hashlib.sha256(mfa_code.encode()).hexdigest(), user["mfa_secret"]):
            return jsonify({"error": "Invalid admin MFA code."}), 401
    token = authenticate_user(user)
    return jsonify({"message": "Signed in.", "token": token, "role": "admin" if user["is_admin"] else "student", "redirect": "admin.html" if user["is_admin"] else "home.html"})


@app.route("/api/profile", methods=["GET"])
@require_auth()
def profile() -> object:
    user = current_user()
    return jsonify({"id": user["id"], "username": user["username"], "full_name": user["full_name"], "email": user["email"], "role": user["role"], "hostel": user["hostel"], "study_year": user["study_year"], "token_id": user["token_id"]})


@app.route("/api/login", methods=["POST"])
@csrf_required
def login() -> object:
    payload = request.get_json(silent=True) or {}
    username = str(payload.get("username", "")).strip()
    password = str(payload.get("password", ""))
    mfa_code = str(payload.get("mfa_code", "")).strip()
    with get_conn() as conn:
        user = conn.execute("SELECT * FROM users WHERE username = ?", (username,)).fetchone()
    if user is None or not check_password_hash(user["password_hash"], password) or not user["is_verified"]:
        app.logger.warning("login failed username=%s", username)
        return jsonify({"error": "Invalid credentials or unverified account."}), 401
    expected_mfa = hashlib.sha256(mfa_code.encode()).hexdigest()
    if not mfa_code or not hmac.compare_digest(expected_mfa, user["mfa_secret"]):
        app.logger.warning("mfa failed username=%s", username)
        return jsonify({"error": "A valid MFA code is required."}), 401
    session.clear()
    session.permanent = True
    session["user_id"] = user["id"]
    session["csrf_token"] = secrets.token_urlsafe(32)
    app.logger.info("login success username=%s admin=%s", username, bool(user["is_admin"]))
    return jsonify({"message": "Signed in.", "is_admin": bool(user["is_admin"])})


@app.route("/api/logout", methods=["POST"])
@csrf_required
def logout() -> object:
    app.logger.info("logout user_id=%s", session.get("user_id"))
    session.clear()
    return jsonify({"message": "Signed out."})


@app.route("/api/request-password-reset", methods=["POST"])
@csrf_required
def request_password_reset() -> object:
    payload = request.get_json(silent=True) or {}
    email = str(payload.get("email", "")).strip().lower()
    with get_conn() as conn:
        user = conn.execute("SELECT id FROM users WHERE email = ?", (email,)).fetchone()
    response = {"message": "If that account exists, reset instructions have been issued."}
    if user:
        token = secrets.token_urlsafe(32)
        session["reset_token_hash"] = hashlib.sha256(token.encode()).hexdigest()
        session["reset_user_id"] = user["id"]
        response["reset_token"] = token
    return jsonify(response)


@app.route("/api/reset-password", methods=["POST"])
@csrf_required
def reset_password() -> object:
    payload = request.get_json(silent=True) or {}
    token = str(payload.get("token", ""))
    password = str(payload.get("password", ""))
    token_hash = hashlib.sha256(token.encode()).hexdigest()
    if len(password) < 10 or not session.get("reset_user_id") or not hmac.compare_digest(token_hash, session.get("reset_token_hash", "")):
        return jsonify({"error": "Invalid reset request or password."}), 400
    with get_conn() as conn:
        conn.execute("UPDATE users SET password_hash = ? WHERE id = ?", (generate_password_hash(password), session["reset_user_id"]))
        conn.commit()
    session.pop("reset_token_hash", None)
    session.pop("reset_user_id", None)
    return jsonify({"message": "Password updated."})


@app.route("/api/predictions", methods=["POST"])
@require_auth()
@csrf_required
def save_prediction() -> object:
    payload = request.get_json(silent=True) or {}
    try:
        score = float(payload.get("score"))
    except (TypeError, ValueError):
        return jsonify({"error": "Invalid prediction."}), 400
    stress_level = str(payload.get("stress_level", "")).strip()
    if stress_level not in {"Low", "Moderate", "High"} or not 0 <= score <= 100:
        return jsonify({"error": "Invalid prediction."}), 400
    with get_conn() as conn:
        conn.execute("INSERT INTO predictions (user_id, stress_level, score, created_at) VALUES (?, ?, ?, ?)",
                     (session["user_id"], stress_level, score, datetime.now(timezone.utc).isoformat()))
        conn.commit()
    return jsonify({"message": "saved"})


@app.route("/api/admin/stats", methods=["GET"])
@require_auth(admin=True)
def admin_stats() -> object:
    with get_conn() as conn:
        group_rows = conn.execute(
            """SELECT u.hostel, u.study_year, COUNT(DISTINCT u.id) AS students,
                      COUNT(DISTINCT CASE WHEN p.stress_level = 'High' THEN u.id END) AS high_stress
               FROM users u LEFT JOIN predictions p ON p.user_id = u.id
               WHERE u.is_admin = 0 AND u.username <> 'guest'
               GROUP BY u.hostel, u.study_year
               ORDER BY u.hostel, u.study_year"""
        ).fetchall()
        rows = conn.execute(
            """SELECT u.study_year, p.stress_level, COUNT(*) AS count
               FROM predictions p JOIN users u ON u.id = p.user_id
               WHERE u.department = 'CSE' GROUP BY u.study_year, p.stress_level"""
        ).fetchall()
        focus_rows = conn.execute(
            """SELECT u.study_year, f.distracted_percentage
               FROM focus_sessions f JOIN users u ON u.username = f.username
               WHERE u.department = 'CSE'"""
        ).fetchall()
    stats = []
    for year in range(1, 5):
        counts = {"Low": 0, "Moderate": 0, "High": 0}
        for row in rows:
            if row["study_year"] == year:
                counts[row["stress_level"]] = row["count"]
        for row in focus_rows:
            if row["study_year"] == year:
                distraction = row["distracted_percentage"]
                level = "High" if distraction >= 50 else "Moderate" if distraction >= 25 else "Low"
                counts[level] += 1
        total = sum(counts.values())
        stats.append({"year": year, "total": total, "stress_percent": round((counts["High"] / total) * 100, 1) if total else 0,
                      "high": counts["High"], "moderate": counts["Moderate"], "low": counts["Low"]})
    ordinal_years = {1: "1st", 2: "2nd", 3: "3rd", 4: "4th"}
    groups = [{
        "hostel": row["hostel"],
        "batch": f"{ordinal_years.get(row['study_year'], str(row['study_year']) + 'th')} Year CSE",
        "students": row["students"],
        "high_stress": row["high_stress"] or 0,
    } for row in group_rows]
    return jsonify({"department": "CSE", "years": stats, "groups": groups})


@app.route("/")
def root() -> object:
    return send_from_directory(BASE_DIR, "index.html")


@app.route("/<path:filename>")
def static_pages(filename: str) -> object:
    if filename.startswith("api/"):
        abort(404)

    user = current_user()
    if filename.lower() == "admin.html" and (user is None or not user["is_admin"]):
        return redirect("/signup.html")

    file_path = BASE_DIR / filename
    if not file_path.exists() or not file_path.is_file():
        abort(404)

    return send_from_directory(BASE_DIR, filename)


@app.route("/api/focus-session", methods=["POST"])
@require_auth()
@csrf_required
def create_focus_session() -> object:
    payload = request.get_json(silent=True) or {}

    username = current_user()["username"]

    try:
        focused_percentage = float(payload.get("focused_percentage", 0))
        distracted_percentage = float(payload.get("distracted_percentage", 0))
        focused_seconds = int(payload.get("focused_seconds", 0))
        distracted_seconds = int(payload.get("distracted_seconds", 0))
        total_seconds = int(payload.get("total_seconds", 0))
    except (TypeError, ValueError):
        return jsonify({"error": "invalid numeric values"}), 400

    session_started_at = str(payload.get("session_started_at", "")).strip()
    session_ended_at = str(payload.get("session_ended_at", "")).strip()

    if not session_started_at or not session_ended_at:
        return jsonify({"error": "session timestamps are required"}), 400

    created_at = datetime.now(timezone.utc).isoformat()

    with get_conn() as conn:
        cleanup_old_rows(conn)
        cursor = conn.execute(
            """
            INSERT INTO focus_sessions (
                username,
                focused_percentage,
                distracted_percentage,
                focused_seconds,
                distracted_seconds,
                total_seconds,
                session_started_at,
                session_ended_at,
                created_at
            ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
            RETURNING id
            """,
            (
                username,
                focused_percentage,
                distracted_percentage,
                focused_seconds,
                distracted_seconds,
                total_seconds,
                session_started_at,
                session_ended_at,
                created_at,
            ),
        )
        inserted = cursor.fetchone()
        conn.commit()

    return jsonify({"message": "saved", "session_id": inserted["id"] if inserted else cursor.lastrowid})


@app.route("/api/focus-session/latest", methods=["GET"])
@require_auth()
def latest_focus_session() -> object:
    username = current_user()["username"]

    with get_conn() as conn:
        cleanup_old_rows(conn)
        row = conn.execute(
            """
            SELECT id, username, focused_percentage, distracted_percentage,
                   focused_seconds, distracted_seconds, total_seconds,
                   session_started_at, session_ended_at, created_at
            FROM focus_sessions
            WHERE username = ?
            ORDER BY id DESC
            LIMIT 1
            """,
            (username,),
        ).fetchone()

        conn.commit()

    if row is None:
        return jsonify({"message": "no session found"}), 404

    return jsonify(dict(row))


@app.route("/api/self-analysis", methods=["POST"])
@require_auth()
@csrf_required
def create_or_update_self_analysis() -> object:
    payload = request.get_json(silent=True) or {}

    username = current_user()["username"]
    log_date = str(payload.get("log_date", "")).strip()
    if not log_date:
        return jsonify({"error": "log_date is required"}), 400

    try:
        study_hours = float(payload.get("study_hours", 0))
        coding_hours = float(payload.get("coding_hours", 0))
        gaming_hours = float(payload.get("gaming_hours", 0))
        physical_activity_hours = float(payload.get("physical_activity_hours", 0))
        social_media_hours = float(payload.get("social_media_hours", 0))
    except (TypeError, ValueError):
        return jsonify({"error": "invalid numeric values"}), 400

    all_values = [
        study_hours,
        coding_hours,
        gaming_hours,
        physical_activity_hours,
        social_media_hours,
    ]
    if any(value < 0 or value > 24 for value in all_values):
        return jsonify({"error": "hours must be between 0 and 24"}), 400

    created_at = datetime.now(timezone.utc).isoformat()

    with get_conn() as conn:
        cleanup_old_rows(conn)
        conn.execute(
            """
            INSERT INTO self_analysis_logs (
                username,
                log_date,
                study_hours,
                coding_hours,
                gaming_hours,
                physical_activity_hours,
                social_media_hours,
                created_at
            ) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
            ON CONFLICT(username, log_date) DO UPDATE SET
                study_hours = excluded.study_hours,
                coding_hours = excluded.coding_hours,
                gaming_hours = excluded.gaming_hours,
                physical_activity_hours = excluded.physical_activity_hours,
                social_media_hours = excluded.social_media_hours,
                created_at = excluded.created_at
            """,
            (
                username,
                log_date,
                study_hours,
                coding_hours,
                gaming_hours,
                physical_activity_hours,
                social_media_hours,
                created_at,
            ),
        )
        conn.commit()

    return jsonify({"message": "saved", "username": username, "log_date": log_date})


@app.route("/api/self-analysis", methods=["GET"])
@require_auth()
def list_self_analysis() -> object:
    username = current_user()["username"]

    try:
        days = int(request.args.get("days", "30"))
    except ValueError:
        days = 30
    days = max(1, min(days, 365))

    from_date = (datetime.now(timezone.utc) - timedelta(days=days)).date().isoformat()

    with get_conn() as conn:
        cleanup_old_rows(conn)
        rows = conn.execute(
            """
            SELECT id, username, log_date, study_hours, coding_hours, gaming_hours,
                   physical_activity_hours, social_media_hours, created_at
            FROM self_analysis_logs
            WHERE username = ? AND log_date >= ?
            ORDER BY log_date ASC
            """,
            (username, from_date),
        ).fetchall()
        conn.commit()

    with get_conn() as conn:
        focus_rows = conn.execute(
            """SELECT id, focused_percentage, distracted_percentage, focused_seconds,
                      distracted_seconds, total_seconds, session_started_at,
                      session_ended_at, created_at
               FROM focus_sessions WHERE username = ? ORDER BY id DESC LIMIT 30""",
            (username,),
        ).fetchall()

    return jsonify({"records": [dict(row) for row in rows], "focus_sessions": [dict(row) for row in focus_rows]})


init_db()

if __name__ == "__main__":
    app.run(debug=True)
